# Generated by Django 5.2.4 on 2025-08-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='create',
            new_name='created',
        ),
    ]
